// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/booth-selection/CardGrid.tsx": () => import("../components/mockups/booth-selection/CardGrid.tsx"),
  "./components/mockups/booth-selection/FloorMap.tsx": () => import("../components/mockups/booth-selection/FloorMap.tsx")
};
